name: analysis-env
channels:
  - conda-forge
  - pytorch
  - r
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - absl-py=2.3.1
  - anyio=4.12.0
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - astunparse=1.6.3
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cctools_impl_osx-64=1030.6.3
  - cctools_osx-64=1030.6.3
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - clang=20.1.8
  - clang-20=20.1.8
  - clang-21=21.1.0
  - clang_impl_osx-64=20.1.8
  - clang_osx-64=20.1.8
  - clangxx=20.1.8
  - clangxx_impl_osx-64=20.1.8
  - clangxx_osx-64=20.1.8
  - comm=0.2.3
  - compiler-rt=20.1.8
  - compiler-rt21=21.1.6
  - compiler-rt21_osx-64=21.1.6
  - compiler-rt_osx-64=20.1.8
  - contourpy=1.3.3
  - cpuonly=2.0
  - cpython=3.11.14
  - curl=8.17.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - ffmpeg=2.8.6
  - filelock=3.20.0
  - flatbuffers=24.12.23
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2025.10.0
  - gast=0.7.0
  - gdk-pixbuf=2.44.4
  - gfortran_impl_osx-64=14.3.0
  - gfortran_osx-64=14.3.0
  - giflib=5.2.2
  - glslang=16.0.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.67.1
  - gsl=2.7
  - h11=0.16.0
  - h2=4.3.0
  - h5py=3.15.1
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isl=0.26
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - kaldi=5.5.1112
  - keras=3.12.0
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.1
  - lcms2=2.17
  - ld64=956.6
  - ld64_osx-64=956.6
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp20.1=20.1.8
  - libclang-cpp21.1=21.1.0
  - libcurl=8.17.0
  - libcxx=21.1.6
  - libcxx-devel=20.1.8
  - libcxx-headers=20.1.8
  - libde265=1.0.15
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran-devel_osx-64=14.3.0
  - libgfortran5=15.2.0
  - libglib=2.86.2
  - libgrpc=1.67.1
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libml_dtypes-headers=0.5.4
  - libnghttp2=1.67.0
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpng=1.6.51
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtensorflow_cc=2.18.0
  - libtensorflow_framework=2.18.0
  - libtiff=4.7.1
  - libtorch=2.6.0
  - libusb=1.0.29
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - llvm-tools=20.1.8
  - llvm-tools-20=20.1.8
  - llvm-tools-21=21.1.0
  - make=4.4.1
  - markdown=3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - mistune=3.1.4
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - namex=0.1.0
  - nb_conda_kernels=2.5.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6
  - nomkl=1.0
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - numpy=2.3.5
  - openfst=1.8.3
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - optree=0.18.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8.3
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.47
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - protobuf=5.28.3
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.2
  - pyobjc-core=12.1
  - pyobjc-framework-cocoa=12.1
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-flatbuffers=25.9.23
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.6.0
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - r-askpass=1.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-blob=1.2.4
  - r-broom=1.0.5
  - r-bslib=0.5.1
  - r-cachem=1.1.0
  - r-callr=3.7.3
  - r-cellranger=1.1.0
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-colorspace=2.1_1
  - r-conflicted=1.2.0
  - r-cpp11=0.4.6
  - r-crayon=1.5.2
  - r-curl=7.0.0
  - r-data.table=1.17.8
  - r-dbi=1.1.3
  - r-dbplyr=2.3.4
  - r-digest=0.6.37
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=0.22
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-fs=1.6.6
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-ggplot2=3.4.4
  - r-glue=1.8.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gtable=0.3.4
  - r-haven=2.5.5
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.9.1
  - r-knitr=1.44
  - r-labeling=0.4.3
  - r-lattice=0.22_7
  - r-lifecycle=1.0.3
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-modelr=0.1.11
  - r-munsell=0.5.0
  - r-nlme=3.1_168
  - r-openssl=2.3.3
  - r-pbdzmq=0.3_14
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-prettyunits=1.2.0
  - r-processx=3.8.6
  - r-progress=1.2.2
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-r6=2.5.1
  - r-ragg=1.5.0
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-repr=1.1.6
  - r-reprex=2.0.2
  - r-rlang=1.1.6
  - r-rmarkdown=2.25
  - r-rstudioapi=0.15.0
  - r-rvest=1.0.3
  - r-sass=0.4.10
  - r-scales=1.2.1
  - r-selectr=0.4_2
  - r-stringi=1.8.7
  - r-stringr=1.5.0
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-textshaping=1.0.3
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.0
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.48
  - r-tzdb=0.4.0
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=2.5.1
  - r-xfun=0.53
  - r-xml2=1.4.0
  - r-yaml=2.3.10
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.2.0
  - rpds-py=0.30.0
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - sdkroot_env_osx-64=14.5
  - sdl2=2.32.56
  - sdl3=3.2.26
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shaderc=2025.4
  - sigtool=0.1.3
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - spirv-tools=2025.4
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tapi=1600.0.11.8
  - tbb=2022.3.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=3.2.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.5.1
  - tk=8.6.13
  - tktable=2.10
  - tomli=2.3.0
  - torchaudio=2.7.0
  - torchvision=0.21.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - werkzeug=3.1.4
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wrapt=2.0.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - blinker==1.9.0
      - click==8.3.1
      - dash==3.3.0
      - dash-bootstrap-components==2.0.4
      - flask==3.1.2
      - itsdangerous==2.2.0
      - narwhals==2.13.0
      - nbstripout==0.8.2
      - plotly==6.5.0
      - retrying==1.4.2
prefix: /Users/nguyenma/miniconda3/envs/analysis-env
